In [1]:
from tile_match_gym.tile_match_env import TileMatchEnv
import numpy as np

In [2]:
env = TileMatchEnv(10, 10, 4, 30, [], [], seed=2)
obs, _ = env.reset()
# print(obs)

In [3]:
num_epi = 0
total_reward = 0
no_elim = 0
num_shuffled = 0
for i in range(100000):
    action = env.action_space.sample()
    next_obs, reward, done, _, info = env.step(action)
    
    if reward == 0:
        no_elim += 1
        
    total_reward += reward
    if info["shuffled"]:
        num_shuffled +=1
        assert env.board.possible_move()
        assert len(env.board.get_colour_lines()) == 0
        
    if done:
        num_epi +=1
        env.reset()

    if i % 1000 == 0 and i > 0:
        print(i)
        print(f"Episode: {num_epi}, Average_Reward: {total_reward / num_epi},Nothing move: {no_elim/i} ")

1000
Episode: 33, Average_Reward: 88.51515151515152,Nothing move: 0.747 
2000
Episode: 66, Average_Reward: 91.24242424242425,Nothing move: 0.7495 
3000
Episode: 100, Average_Reward: 87.16,Nothing move: 0.752 
4000
Episode: 133, Average_Reward: 85.21052631578948,Nothing move: 0.75425 
5000
Episode: 166, Average_Reward: 86.59036144578313,Nothing move: 0.7528 
6000
Episode: 200, Average_Reward: 84.755,Nothing move: 0.7561666666666667 
7000
Episode: 233, Average_Reward: 84.0901287553648,Nothing move: 0.759 
8000
Episode: 266, Average_Reward: 85.61278195488721,Nothing move: 0.76 
9000
Episode: 300, Average_Reward: 84.87,Nothing move: 0.761 
10000
Episode: 333, Average_Reward: 86.01801801801801,Nothing move: 0.7597 
11000
Episode: 366, Average_Reward: 86.59016393442623,Nothing move: 0.7596363636363637 
12000
Episode: 400, Average_Reward: 86.485,Nothing move: 0.75975 
13000
Episode: 433, Average_Reward: 86.26789838337183,Nothing move: 0.7608461538461538 
14000
Episode: 466, Average_Reward: 86

In [ ]:
num_shuffled

7458

In [ ]:
next_obs, reward, done, _, info = env.step(6)
assert np.array_equal(next_obs, np.array([[[2, 3, 1, 2, 1],
                                           [2, 2, 3, 1, 2],
                                           [3, 2, 1, 2, 3]],                            
                                           [[1, 1, 1, 1, 1],
                                           [1, 1, 1, 1, 1],
                                           [1, 1, 1, 1, 1]]]))

assert reward == 6
assert not done
assert info == {'is_combination_match': False,
                'num_new_specials': 0,
                'num_new_specials': 0,
                'num_specials_activated': 0,
                'shuffled': False,
                'num_moves_left': 3}

IndexError: list index out of range

In [ ]:
next_obs, reward, done, _, info = env.step(16)

swapped coords
[[[2 3 1 2 1]
  [2 2 1 3 2]
  [3 2 1 2 3]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]
colour_match
[[[2 3 1 2 1]
  [2 2 1 3 2]
  [3 2 1 2 3]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]
[[(0, 2), (1, 2), (2, 2)]] ['normal']
gravity
[[[2 3 0 2 1]
  [2 2 0 3 2]
  [3 2 0 2 3]]

 [[1 1 0 1 1]
  [1 1 0 1 1]
  [1 1 0 1 1]]]
refill
[[[2 3 3 2 1]
  [2 2 3 3 2]
  [3 2 2 2 3]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]
colour_match
[[[2 3 3 2 1]
  [2 2 3 3 2]
  [3 2 2 2 3]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]
[[(2, 1), (2, 2), (2, 3)]] ['normal']
gravity
[[[2 0 0 0 1]
  [2 3 3 2 2]
  [3 2 3 3 3]]

 [[1 0 0 0 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]
refill
[[[2 1 3 1 1]
  [2 3 3 2 2]
  [3 2 3 3 3]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]
colour_match
[[[2 1 3 1 1]
  [2 3 3 2 2]
  [3 2 3 3 3]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]
[[(0, 2), (1, 2), (2, 2), (2, 3), (2, 4)]] ['bomb']
gravity
[[[2 1 0 0 0]
  [2 3 0 1 1]
  [3 2 3 2 2]]

 [[1 1 0 0 0]
  [1 1 0 1 1]
  [1

In [ ]:
assert np.array_equal(next_obs, np.array([[[2, 3, 1, 3, 2],
                                           [2, 2, 1, 2, 1],
                                           [3, 1, 3, 3, 2]],
                                          [[1, 1, 1, 1, 1],
                                           [1, 1, 1, 1, 1],
                                           [1, 1, 1, 1, 1]]]))
assert reward == 18
assert not done
info = {'is_combination_match': False,
        'num_new_specials': 1,
        'num_specials_activated': 1,
        'shuffled': False,
        'num_moves_left': 2}

In [ ]:
# No move possible
next_obs, reward, done, _, info = env.step(19)
# Combination match

# Combination match -> activate special/create special.

swapped coords
[[[2 3 1 3 2]
  [2 2 1 2 1]
  [3 3 1 3 2]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]
colour_match
[[[2 3 1 3 2]
  [2 2 1 2 1]
  [3 3 1 3 2]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]
[[(0, 2), (1, 2), (2, 2)]] ['normal']
gravity
[[[2 3 0 3 2]
  [2 2 0 2 1]
  [3 3 0 3 2]]

 [[1 1 0 1 1]
  [1 1 0 1 1]
  [1 1 0 1 1]]]
refill
[[[2 3 2 3 2]
  [2 2 2 2 1]
  [3 3 3 3 2]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]
colour_match
[[[2 3 2 3 2]
  [2 2 2 2 1]
  [3 3 3 3 2]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]
[[(2, 0), (2, 1), (2, 2), (2, 3)]] ['horizontal_laser']
gravity
[[[0 3 0 0 2]
  [2 2 2 3 1]
  [2 3 2 2 2]]

 [[0 1 0 0 1]
  [1 1 1 1 1]
  [1 3 1 1 1]]]
refill
[[[2 3 2 1 2]
  [2 2 2 3 1]
  [2 3 2 2 2]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 3 1 1 1]]]
colour_match
[[[2 3 2 1 2]
  [2 2 2 3 1]
  [2 3 2 2 2]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 3 1 1 1]]]
[[(0, 0), (1, 0), (2, 0)], [(0, 2), (1, 2), (2, 2), (2, 3), (2, 4)]] ['normal', 'bomb']
gravity
[[[0 3 0 0 0]
  [0 2 0

In [ ]:
assert np.array_equal(next_obs, np.array([[[1, 1, 2, 2, 1],
                                           [2, 2, 3, 1, 2],
                                           [1, 3, 2, 3, 1]],
                                           [[1, 1, 1, 1, 1],
                                           [1, 1, 1, 1, 1],
                                           [1, 3, 4, 1, 1]]]))
assert reward == 18
assert info == {
    'is_combination_match': False,
    'num_new_specials': 2,
    'num_specials_activated': 0,
    'shuffled': False,
    'num_moves_left': 1
    }

In [ ]:
next_obs, reward, done, _, info = env.step(19)

swapped coords
[[[1 1 2 2 1]
  [2 2 3 1 2]
  [1 2 3 3 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 4 3 1 1]]]
combo match
[[[0 0 0 2 1]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 1 1]
  [0 0 0 0 0]
  [0 0 0 0 0]]]
gravity
[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 2 1]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 1 1]]]
refill
[[[2 2 1 2 3]
  [1 3 1 1 3]
  [1 3 1 2 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]
colour_match
[[[2 2 1 2 3]
  [1 3 1 1 3]
  [1 3 1 2 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]
[[(0, 2), (1, 2), (2, 2)]] ['normal']
gravity
[[[2 2 0 2 3]
  [1 3 0 1 3]
  [1 3 0 2 1]]

 [[1 1 0 1 1]
  [1 1 0 1 1]
  [1 1 0 1 1]]]
refill
[[[2 2 2 2 3]
  [1 3 3 1 3]
  [1 3 3 2 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]
colour_match
[[[2 2 2 2 3]
  [1 3 3 1 3]
  [1 3 3 2 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]
[[(0, 0), (0, 1), (0, 2), (0, 3)]] ['horizontal_laser']
gravity
[[[0 2 0 0 3]
  [1 3 3 1 3]
  [1 3 3 2 1]]

 [[0 3 0 0 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]
refill
[[[2 2 1 1 3]
  

In [ ]:
next_obs

array([[[2, 2, 1, 1, 3],
        [1, 3, 3, 1, 3],
        [1, 3, 3, 2, 1]],

       [[1, 3, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [ ]:
assert reward == 20
assert np.array_equal(next_obs, np.array([[[2, 2, 1, 1, 3],
                                          [1, 3, 3, 1, 3],
                                          [1, 3, 3, 2, 1]],
                                          [[1, 3, 1, 1, 1],
                                          [1, 1, 1, 1, 1],
                                          [1, 1, 1, 1, 1]]]))
assert done

assert info == {
    'is_combination_match': True,
    'num_new_specials': 1,
    'num_specials_activated': 0,
    'shuffled': False,
    'num_moves_left': 0
}

In [ ]:
from tile_match_gym.board import Board 
from multiprocessing import Pool
def process_combination(combination):
    count_s, count_s_, count_m = 0, 0, 0
    b = Board(4, 4, 3,[], [])
    b.board = np.array(combination).reshape(4, 4)
    no_poss_move = not b.possible_move()
    has_match = len(b.get_colour_lines()) > 0
    if has_match or no_poss_move:
        count_s = 1
    if not has_match and no_poss_move:
        count_s_= 1
    if has_match:
        count_m = 1

    return count_s, count_s_, count_m

In [ ]:
num_invalid_s, num_valid_states_no_move, num_states_w_move_and_match = 0, 0, 0
with Pool() as pool:
    results = pool.map(process_combination, x)

    # Aggregate results from parallel processes

    for result in results:
        num_invalid_s += result[0]
        num_valid_states_no_move += result[1]
        num_states_w_move_and_match += result[2]

print(len(x) - num_invalid_s, num_valid_states_no_move, num_states_w_move_and_match)

8426718 57420 34562583


In [ ]:
len(x)

531441

In [ ]:
count_s

13303

In [ ]:
count_s_

6377

In [ ]:
count_m

2458

In [ ]:
count_poss

6380

In [ ]:
for i, combination in enumerate(x):
    b = Board(3, 3, 3, ["vertical_laser"], [])
    b.board = np.array(combination).reshape(3,3)
    no_poss_move = not b.possible_move()
    has_match = len(b.get_colour_lines()) > 0
    if has_match or no_poss_move:
        count_tot -= 1
    if has_match:
        count_m += 1
    if not no_poss_move:
        count_poss += 1

    # if i % 1000 == 1:
    #     print(i, count_m / i, count_poss / i, count_tot, b.board)

    
        


    

In [ ]:
valid_arr

10077696

In [ ]:

board = Board(10, 10, 5)  # cookie , and vertical laser, horizontal laser, bomb
board.board = np.array([[4, 4, 5, 4, 2, 2, 6, 6, 3, 3],
                        [3, 6, 3, 6, 3, 4, 5, 4, 2, 2],
                        [6, 5, 6, 4, 6, 3, 4, 5, 2, 3],
                        [2, 4, 6, 2, 3, 4, 6, 3, 4, 3],
                        [2, 5, 2, 3, 4, 4, 2, 6, 5, 6],
                        [4, 5, 3, 4, 6, 3, 5, 2, 5, 6],
                        [4, 4, 3, 2, 4, 5, 4, 5, 3, 5],
                        [5, 6, 4, 2, 5, 4, 6, 4, 3, 2],
                        [4, 5, 5, 6, 3, 4, 6, 3, 5, 6],
                        [4, 4, 5, 4, 6, 5, 2, 2, 4, 6]])

old_board = deepcopy(board.board)
assert board.check_move_validity((1,1), (1, 2))
assert board.check_move_validity((1,1), (2, 1))
assert np.array_equal(board.board, old_board)